### ISSUE TITLE
N26 Error : panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by fschmutz** [JHeimbach/csvtomt940#2]
Hi,

First, thanks for your tool, amazing to find this for me.
But when i tried, i received some error, can you help me on this ?

~# go/bin/csvtomt940 n26-csv-transactions-test.csv --bank-type n26 --n26-iban DEXXXX --n26-start-saldo XXXXXX
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/JHeimbach/csvtomt940/banks/ing.getAccountNumber(0xc00006ad00, 0xd, 0xd, 0xd, 0x0, 0x0, 0x40ea19)
	/root/go/pkg/mod/github.com/!j!heimbach/csvtomt940@v0.0.0-20210910093430-26b8e2ab13a3/banks/ing/bank.go:82 +0x151
github.com/JHeimbach/csvtomt940/banks/ing.(*Ing).ParseCsv(0xc000048420, 0xc00000e028, 0x1)
	/root/go/pkg/mod/github.com/!j!heimbach/csvtomt940@v0.0.0-20210910093430-26b8e2ab13a3/banks/ing/bank.go:30 +0x3b0
main.main()
	/root/go/pkg/mod/github.com/!j!heimbach/csvtomt940@v0.0.0-20210910093430-26b8e2ab13a3/main.go:43 +0x40f

**Comment by JHeimbach** [comment]
Hey, 

glad you like it :)

Can you try running it with the options before the csv file?

`go/bin/csvtomt940 --bank-type n26 --n26-iban DEXXXX --n26-start-saldo XXXXXX n26-csv-transactions-test.csv`

**Comment by fschmutz** [comment]
Oh... my bad, you right ! sorry :)
It works perfectly, maybe adding some exemple in readme should be great.
Have a good day!

**Comment by JHeimbach** [comment]
Good idea, i added an example to the readme.

also the error message should be clearer now :)
